#!/bin/sh

module="universeII"
modname="universeII"
device="vmeex"
group="users"
version=`uname -r`
kernel=kernel-$version

clear
printf "Loading %s module...\n" $module
case $version in
    2.2.* | 2.4.*) /sbin/insmod $kernel/$module.o || exit 1;;
    2.6.*) /sbin/insmod $kernel/$module.ko || exit 1;;
    3.*.*) /sbin/insmod $kernel/$module.ko || exit 1;;
esac

if [ -d /dev/$device ]
then
    printf "Removing old device files...\n"
    rm -f /dev/$device/ctl
    rmdir /dev/$device
fi

major=`cat /proc/devices | awk "\\$2==\"$modname\" {print \\$1}"`

printf "Creating new device files...\n"
mkdir /dev/$device
mknod /dev/$device/ctl   c $major 0

# set appropriate group/permissions
chown root /dev/$device
chown root /dev/$device/*
chgrp users /dev/$device
chgrp users /dev/$device/*
chmod 666 /dev/$device/*

printf "Installation complete\n"
