#!/bin/sh

module="universeII"
device="vmeex"

printf "Unloading %s module...\n" $module
/sbin/rmmod $module || exit 1

if [ -d /dev/$device ]
then
    printf "Removing device files...\n"
    rm -f /dev/$device/ctl
    rmdir /dev/$device
fi

printf "Removed %s module\n" $module
